<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.
Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does! 
You can return all of these exercises in a single Jupyter Notebook, if you wish.

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/numpylogo.png" width="250"/>

<b>NOTE!</b> For each subtask, save the result into a separate variable!

In [7]:
# setup all needed modules and configurations
import numpy as np
import random
import pandas as pd

# re-style the NumPy arrays
# remember to install needed module first:
%load_ext numpy_html

Run the cell below to enable custom style for NumPy arrays:

In [8]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<b>Tip: creating a list with Python code is usually something like this:</b>

<pre>
numbers = []

for x in range(0, 5):
    numbers.append(x)
</pre>

In [9]:
# Using loop  to create a list of 15 ones
one_arr = []

for _ in range(15):
    one_arr.append(1)
print(one_arr)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [10]:
# Using loop  to create a list of 15 sevens
seven_arr = []
seven = 7
for _ in range(15):
    seven_arr.append(seven)
print(seven_arr)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [11]:
# 3- Create a list numbers from 100 to 150 without using " Numpy"

number = [i for i in range(100, 151)]
print(number)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [12]:
#-5  Create list of years that are dividable by 4 between 1950 and 2020
years = [i for i in range(1950, 2021) if i % 4 == 0]
years

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



In [13]:
# exercise 1.2, create lists WITH NumPy
# use a# 1- Create a list of 15 ones using " Numpy"
zero = np.zeros(15)
zero



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# 2- Create a list of  15 numbers of 1s using " Numpy"
one = np.ones(15)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
# 3- Create a array of 15 numbers 7 using " Numpy"
seven = np.full(15, 7)
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [16]:
# 3- Create a array of 15 numbers 7 using " Numpy"
seven = np.full(15, 7)
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [17]:
# 4- Create a list numbers from 100 to 150 using " Numpy"
number = np.arange(100, 151)
number

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [18]:
# 5- Create a list of even number between 0 to 100 numbers using " Numpy"
even = np.arange(0, 101, 2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [19]:
# 5- Create a list of even number between 0 to 100 numbers using " Numpy"
even = np.arange(0, 101, 2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [20]:
# 6- Create list of years that are dividable by 4 between 1950 and 2020 using " Numpy"
numbers = np.arange(1950, 2021)
years = numbers[numbers % 4 == 0]
years


array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>

<h3><b>3. Let's try out NumPy vectors and matrices:</b></h3>

- Create a NumPy vector (list) containing these values:<br>
<b><i>5, 16, 9, 2, 19, 18, 11, 7</i></b><br>
    - Use argmax() to find the position index of the largest value in the vector, and print it
<br><br>
- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python!

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


In [21]:
# Creating  a NumPy vector (list) containing these values: 5, 16, 9, 2, 19, 18, 11, 7
# Use argmax() to find the position index of the largest value in the vector, and print it

vect = np.array([5, 16, 9, 2, 19, 18, 11, 7])

position = np.argmax(vect)
print(position)

# The position index of the 19 in the vector is 4. 

4


In [22]:
# Creating  a 7x7 matrix, with values from 1 to 49
matrix = np.arange(1, 50).reshape(7, 7)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [23]:
# Extra tasks:
# Creating 7x7 matrix, with values from 1 to 49 without using "Numpy"

# I got the general idea from there: https://stackoverflow.com/questions/60019226/creating-a-matrix-in-python-with-a-range-of-numbers

matrix = [[i + j for i in range(7)] for j in range(1, 49, 7)]
matrix

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [24]:
# Generating 8x8 random number matrix, values between 0 and 5
matrix = np.random.randint(0, 6, size=(8, 8))
matrix

array([[2, 2, 5, 2, 4, 3, 0, 1],
       [5, 0, 5, 1, 4, 2, 4, 1],
       [5, 0, 0, 1, 2, 3, 4, 3],
       [5, 3, 0, 5, 5, 5, 4, 5],
       [1, 5, 3, 0, 1, 5, 2, 1],
       [5, 1, 0, 0, 3, 3, 4, 4],
       [3, 1, 2, 2, 0, 3, 2, 5],
       [5, 1, 0, 0, 4, 0, 5, 1]], dtype=int32)

In [25]:
# Creating  8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)
matrix = np.random.randint(-3, 4, (8, 8))   
matrix

array([[ 0,  0,  2,  3,  2,  2,  3,  2],
       [-3,  1, -3,  2, -3,  1,  3,  1],
       [-1,  2,  1,  0, -2, -2,  2,  1],
       [ 3,  3,  3,  0, -3,  1,  3, -3],
       [-1, -2,  1, -1, -3,  2,  0, -1],
       [ 0,  3,  3,  1, -2,  0,  2,  1],
       [ 0,  0, -2,  3,  3,  2,  2, -2],
       [-3, -2, -1,  2,  0, -2,  2,  2]], dtype=int32)

In [26]:
#  array (list/vector) of 10 values between value 0 and 1 
array = np.linspace(0, 1, 10)
array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [27]:
# Creating 10x10 matrix between values 0 and 5
matrix = np.linspace(0, 5, 100).reshape(10, 10)
matrix

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

In [28]:
# Creating 10x10 matrix between values 0 and 5 without using "Numpy"
# Since I am not sure is it acceptable or not, I did not put it here, but it is in my numpy.ipynb file.
# I will wait for the feedback.


In [29]:
numbers = [23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51]
matrix = np.array(numbers).reshape(3, 5)

matrix

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well!


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [30]:
# exercise 1.4, linspace
# use different variable names for each subtask
# you can also make new code cells if you need


<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [31]:
numbers = [23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51]
matrix3_5 = np.array(numbers).reshape(3, 5)
matrix3_5


array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [32]:
matrix8_16 = np.arange(128, 256).reshape(8, 16)
matrix8_16


array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [33]:
matrix10_10 = np.linspace(0.05, 5, 100).reshape(10, 10)
matrix10_10

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

In [34]:
# exercise # dataset = np.arange(1, 37).reshape(6, 6)
dataset = np.arange(1, 37).reshape(6, 6)
dataset


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [35]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [36]:
matrix_1 = dataset[3:, 3:]
matrix_1


array([[22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [37]:
# exercise 1.6c, matrix slicing
matrix_2 = dataset[:4, 3]
matrix_2

array([ 4, 10, 16, 22])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [38]:
matrix_3 =  dataset[2, :]
matrix_3

array([13, 14, 15, 16, 17, 18])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [39]:
matrix_4 = dataset[3:, :]
matrix_4

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises <u><b>without</b></u> NumPy in Python!

<br>
<b>Note:</b> Don't create a new dataset when adding 50 to all values in the array, use the existing one.
<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [40]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)
dataset_2
# use different variable names for each subtask
# you can also make new code cells if you need


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [41]:
# 1- Adding 50 to all values in the array
matrix_1 = dataset_2 + 50
matrix_1

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [42]:
# 2-Getting the sum of all values in the array
sum = np.sum(dataset_2)
sum

np.int64(1225)

In [43]:
# 3 Getting sum of only odd numbers in the matrix
odd_sum = dataset_2[dataset_2 % 2 != 0].sum()
odd_sum


np.int64(625)

In [44]:
# 4- Getting the standard deviation of the values in the matrix
std = dataset_2.std()   
std

np.float64(14.142135623730951)

In [45]:
# 5- Getting the sum of all values by ROW in the matrix
sum_row = dataset_2.sum(axis=1)
sum_row

array([ 28,  77, 126, 175, 224, 273, 322])

In [46]:
# 6- Getting the sum of all values by COLUMN in the matrix
sum_column = dataset_2.sum(axis=0)
sum_column

array([154, 161, 168, 175, 182, 189, 196])

<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


In [47]:
# Creating 15x15 matrix with random values
matrix_saved = np.random.rand(15, 15)
print(matrix_saved)


# Saving matrix to file
np.savetxt('matrix.txt', matrix_saved)

# print the shape of the matrix
print(matrix_saved.shape)


[[0.71599448 0.08575028 0.11196299 0.30552156 0.75151641 0.10698602
  0.40202509 0.69706711 0.18841588 0.89956057 0.75087625 0.75700205
  0.1007424  0.24463454 0.74607757]
 [0.29664874 0.85773703 0.19267717 0.2278676  0.6498918  0.70139015
  0.99382149 0.80987008 0.31769911 0.17916284 0.87364293 0.52331843
  0.58214312 0.38082429 0.57131652]
 [0.60747656 0.64595295 0.84353799 0.79580022 0.7352943  0.09731055
  0.44716455 0.32747322 0.52909487 0.86140295 0.52824491 0.86959986
  0.8597137  0.83467694 0.21376574]
 [0.77678632 0.19894348 0.25040377 0.41959985 0.13882059 0.93528579
  0.49001446 0.06532464 0.41662036 0.9047911  0.48299068 0.46610006
  0.37007974 0.21099509 0.86490973]
 [0.82465607 0.3031463  0.41538442 0.80216217 0.18700286 0.82208843
  0.78623499 0.69258378 0.24962216 0.24149601 0.63180293 0.63558953
  0.64674473 0.53606979 0.28315125]
 [0.84739669 0.78125935 0.05797345 0.22560034 0.87374125 0.55786832
  0.97923445 0.29419653 0.43026767 0.49062086 0.60562598 0.56295434
  0.

In [48]:
# Loading matrix from matrix.txt file to read.py file

# Load matrix from file
matrix_loaded = np.loadtxt('matrix.txt')
print(matrix_loaded)

[[0.71599448 0.08575028 0.11196299 0.30552156 0.75151641 0.10698602
  0.40202509 0.69706711 0.18841588 0.89956057 0.75087625 0.75700205
  0.1007424  0.24463454 0.74607757]
 [0.29664874 0.85773703 0.19267717 0.2278676  0.6498918  0.70139015
  0.99382149 0.80987008 0.31769911 0.17916284 0.87364293 0.52331843
  0.58214312 0.38082429 0.57131652]
 [0.60747656 0.64595295 0.84353799 0.79580022 0.7352943  0.09731055
  0.44716455 0.32747322 0.52909487 0.86140295 0.52824491 0.86959986
  0.8597137  0.83467694 0.21376574]
 [0.77678632 0.19894348 0.25040377 0.41959985 0.13882059 0.93528579
  0.49001446 0.06532464 0.41662036 0.9047911  0.48299068 0.46610006
  0.37007974 0.21099509 0.86490973]
 [0.82465607 0.3031463  0.41538442 0.80216217 0.18700286 0.82208843
  0.78623499 0.69258378 0.24962216 0.24149601 0.63180293 0.63558953
  0.64674473 0.53606979 0.28315125]
 [0.84739669 0.78125935 0.05797345 0.22560034 0.87374125 0.55786832
  0.97923445 0.29419653 0.43026767 0.49062086 0.60562598 0.56295434
  0.

<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [49]:
# advanced ext# Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots (for example: -100)
matrix0_50 = np.random.randint(0, 51, size=(15, 15))
matrix0_50


array([[ 0, 11, 44, 41, 28, 30, 42, 32, 12, 31, 38,  7,  3,  0, 20],
       [40, 40,  9, 47, 23, 37,  8, 48, 36, 26, 35, 25, 11, 15, 31],
       [27, 35, 41, 26, 29, 12, 14, 12, 35, 19,  0, 12, 34,  3, 47],
       [ 0, 39, 12,  4, 33, 15, 48, 20, 30, 20, 35, 36, 29,  2, 39],
       [28, 47,  2, 46, 13, 18, 29, 21, 28, 23, 18, 38, 32, 18, 10],
       [ 6, 15, 30, 11, 21, 17, 28,  1, 50, 27, 12, 39, 11, 30, 10],
       [16, 44, 17, 29, 13, 24, 50, 25,  2,  9, 25, 12, 26, 25, 48],
       [33,  0, 47,  2, 33, 10, 21,  9, 45, 46, 11, 46, 49, 40, 16],
       [11,  0, 41,  1, 44, 25,  0, 37, 35,  5, 17, 35, 19, 40, 33],
       [38, 33, 39, 11, 11, 34,  2, 15, 29, 12, 40, 43, 32,  3,  0],
       [ 4, 23,  5, 24, 14, 11, 18, 34, 40, 41, 33, 34,  3, 44,  0],
       [41, 10, 41, 44, 41, 21, 40, 18, 45, 36, 43, 48,  4, 29,  7],
       [32, 32, 26, 30,  4,  3, 13,  1, 37,  7, 19, 30, 39, 29, 27],
       [18,  0, 16, 16, 31, 32,  7, 14, 26, 11,  2, 22, 27,  7, 48],
       [31,  0, 20, 38, 27, 31, 14, 17, 25, 14, 50, 17, 44, 30, 13]],
      dtype=int32)

In [50]:

n = 10

# I took this code from Stackoverflow and modified it  for my task. 
mask = np.random.permutation(np.array([True]*n + [False]*(matrix.size-n))).reshape(matrix.shape)
matrix[mask] = -100

matrix




# Replacing the faulty numbers with  zeros in the matrix
matrix[matrix == 0] = -100
matrix


array([[-100, -100, -100,   31, -100],
       [-100, -100, -100, -100,   97],
       [  41,   32, -100, -100,   51]])

In [51]:
# Now replace the faulty numbers with  zeros in the matrix
matrix[matrix == 0] = -100
matrix

array([[-100, -100, -100,   31, -100],
       [-100, -100, -100, -100,   97],
       [  41,   32, -100, -100,   51]])

<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [52]:
# Manufacturing years of 10 cars, values between 2010 and 2020
years = np.random.randint(2010, 2021, 10)
years




array([2014, 2013, 2012, 2012, 2012, 2015, 2020, 2010, 2018, 2014],
      dtype=int32)

In [53]:
# Selling price of 10 cars, prices between 2000€ and 60000€
prices = np.random.randint(2000, 60001, 10)
prices

array([26868, 52406, 15787,  4114, 40754,  5166, 14840, 30825, 36603,
        2800], dtype=int32)

In [54]:
# Sort the years and prices
sort = np.argsort(years)
sorted_years = years[sort]
sorted_prices = prices[sort]

# Creating a DataFrame
df = pd.DataFrame({'Year': sorted_years, 'Price': sorted_prices})
df

Year  Price
0  2010  30825
1  2012   4114
2  2012  40754
3  2012  15787
4  2013  52406
5  2014  26868
6  2014   2800
7  2015   5166
8  2018  36603
9  2020  14840

<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




### 1. np.repeat()

In [55]:
# advanced extra exercise 4


# Repeats each element in an array a specified number of times.
# when you need to duplicate data for creating patterns or expanding datasets

# Example:
# Create an array of 5 elements
array = np.array([1, 2, 3, 4, 5])
array



array([1, 2, 3, 4, 5])

In [56]:
repeat = np.repeat(array, 3)
repeat

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

### 2. np.ravel()

In [62]:
# Converts a multi-dimensional array into a flat (1D) array. 
# It is useful when you need to process data as a single dimension, like for machine learning models.
ravel_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ravel_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:

flatten = np.ravel(ravel_array)
flatten

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. np.hsplit(), np.vsplit(), np.hstack, np.vstack()

In [ ]:
# hsplit(): Splits an array into equal parts along columns.
# vsplit(): Splits an array into equal parts along rows.
# hstack(): Stacks arrays side by side (columns).
# vstack(): Stacks arrays on top of each other (rows).

In [65]:
# Creating  a 4x4 matrix
matrix = np.arange(1, 17).reshape(4, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
# Split the matrix into two equal parts along columns
hsplit = np.hsplit(matrix, 2)
hsplit


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [68]:
# Example 2:
# Creating a 6x6 matrix
matrix6_6 = np.arange(1, 37).reshape(6, 6)
matrix6_6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [69]:
# Split the matrix into two equal parts along rows
vsplit = np.vsplit(matrix6_6, 2)
vsplit


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [70]:
# Example 3: 

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stacking the arrays side by side
hstack = np.hstack((array1, array2))
hstack


array([1, 2, 3, 4, 5, 6])

In [72]:
# Stacking the arrays on top of each other
vstack = np.vstack((array1, array2))
vstack

array([[1, 2, 3],
       [4, 5, 6]])

### 4. np.transpose()

In [73]:
# np.transpose()
# Swaps rows and columns in a matrix.  
arr = np.array([[1, 2], [3, 4]])
np.transpose(arr)  


array([[1, 3],
       [2, 4]])

### 5. np.round()

In [74]:
# It is used when formatting results, like rounding predictions to two decimals.

# Example:
arr = np.array([1.123, 2.456])
np.round(arr, 1) 

array([1.1, 2.5])

### 6. np.expand_dims(), np.squeeze()

In [75]:
# expand_dims(): Adds a new dimension to an array.
# squeeze():  Adds a new dimension to an array.

# Example:
arr = np.array([1, 2, 3])
print(arr.shape)

(3,)


In [76]:
# Expanding the dimensions of the array
new_arr = np.expand_dims(arr, axis=1)

new_arr.shape


(3, 1)

In [78]:
# Example 2:

arr = np.array([[[1, 2], [3, 4]]])
print(arr.shape)

# Removing the extra dimension
new_arr = np.squeeze(arr)

print(new_arr.shape)


(1, 2, 2)
(2, 2)


### 7. np.digitiz

In [79]:
# It simplifies complex data, reduces noise, and prepares data for specific algorithms.

a = np.array([1.2, 2.4, 3.6, 4.8])
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0])

# using np.digitize() method
gfg = np.digitize(a, bins)

gfg

array([1, 2, 3, 4])