<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.
Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does! 
You can return all of these exercises in a single Jupyter Notebook, if you wish.

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/numpylogo.png" width="250"/>

<b>NOTE!</b> For each subtask, save the result into a separate variable!

In [103]:
# setup all needed modules and configurations
import numpy as np
import random
import pandas as pd

# re-style the NumPy arrays
# remember to install needed module first:
%load_ext numpy_html

The numpy_html extension is already loaded. To reload it, use:
  %reload_ext numpy_html


Run the cell below to enable custom style for NumPy arrays:

In [104]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<b>Tip: creating a list with Python code is usually something like this:</b>

<pre>
numbers = []

for x in range(0, 5):
    numbers.append(x)
</pre>

In [105]:
# Using loop to create a list of 15 ones

values=[]

for i in range(15):
 values.append(1)
   
values

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [106]:
# Using loop  to create a list of 15 sevens
arraySeven = []

for i in range(15):
    arraySeven.append(7)
print(arraySeven)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [107]:
# 3- Create a list numbers from 100 to 150 without using " Numpy"

number = [i for i in range(100, 151)]
print(number)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [108]:
#-5  Create list of years that are dividable by 4 between 1950 and 2020
years = [i for i in range(1950, 2021) if i % 4 == 0]
years

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



In [109]:
# exercise 1.2, create lists WITH NumPy
#1- Creating a list of 15 ones using " Numpy"
zero = np.zeros(15)
zero



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
# 2- Creating a list of  15 numbers of 1s using " Numpy"
one = np.ones(15)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [111]:
# 3 Creating  a array of 15 numbers 7 using " Numpy"
seven = np.full(15, 7)
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [112]:
# 3- Creating  a array of 15 numbers 7 using " Numpy"
seven = np.full(15, 7)
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [113]:
# 4- Creating a list numbers from 100 to 150 using " Numpy"
number = np.arange(100, 151)
number

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [114]:
# 5- Creating a list of even number between 0 to 100 numbers using " Numpy"
even = np.arange(0, 101, 2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [115]:
# 5- Creating a list of even number between 0 to 100 numbers using " Numpy"
even = np.arange(0, 101, 2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [116]:
# 6- Creating list of years that are dividable by 4 between 1950 and 2020 using " Numpy"
numbers = np.arange(1950, 2021)
years = numbers[numbers % 4 == 0]
years


array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>

<b> Based on my experience, working with NumPy is quite easy and saves time. But, plain python code is good for a deeper understanding of Python logic and concept. <b>

<h3><b>3. Let's try out NumPy vectors and matrices:</b></h3>

- Create a NumPy vector (list) containing these values:<br>
<b><i>5, 16, 9, 2, 19, 18, 11, 7</i></b><br>
    - Use argmax() to find the position index of the largest value in the vector, and print it
<br><br>
- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python!

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


In [117]:
# Creating  a NumPy vector (list) containing these values: 5, 16, 9, 2, 19, 18, 11, 7
# Use argmax() to find the position index of the largest value in the vector, and print it

vector = np.array([5, 16, 9, 2, 19, 18, 11, 7])

position = np.argmax(vector)
position

# The position index of the 19 in the vector is 4. 

np.int64(4)

In [118]:
# Creating  a 7x7 matrix, with values from 1 to 49
matrix7_7 = np.arange(1, 50).reshape(7, 7)
matrix7_7

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [119]:
# Extra tasks:
# Creating 7x7 matrix, with values from 1 to 49 without using "Numpy"

# I got the general idea from there: https://stackoverflow.com/questions/60019226/creating-a-matrix-in-python-with-a-range-of-numbers

Extra_task = [[i + j for i in range(7)] for j in range(1, 49, 7)]
Extra_task

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [120]:
# Generating 8x8 random number matrix, values between 0 and 5
matrix8_8 = np.random.randint(0, 6, size=(8, 8))
matrix8_8

array([[3, 5, 5, 4, 5, 2, 3, 2],
       [4, 4, 3, 5, 1, 1, 4, 4],
       [4, 4, 3, 4, 3, 3, 0, 0],
       [1, 1, 2, 4, 5, 3, 5, 1],
       [5, 3, 3, 2, 0, 3, 5, 0],
       [2, 1, 4, 5, 4, 4, 2, 3],
       [1, 3, 5, 3, 1, 0, 5, 4],
       [4, 0, 3, 1, 4, 2, 1, 0]], dtype=int32)

In [121]:
# Creating  8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)
normal_matrix = np.random.randint(-3, 4, (8, 8))   
normal_matrix

array([[-2,  3,  0,  1,  2, -3, -2,  0],
       [-2,  1, -1, -1,  0,  1, -2, -3],
       [ 2, -1,  3,  1,  0,  2, -2, -2],
       [-1,  3,  1, -2,  1, -2,  0,  0],
       [ 0,  2, -3, -1, -1, -1,  0,  1],
       [-2, -1,  2, -1, -2,  1,  1, -1],
       [-3, -2, -3, -2, -1,  0,  3,  0],
       [-1, -3,  0,  1,  2,  3, -2, -2]], dtype=int32)

<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well!


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [122]:
# exercise 1.4, linspace
# use different variable names for each subtask
# you can also make new code cells if you need


In [123]:
#  array (list/vector) of 10 values between value 0 and 1 
array = np.linspace(0, 1, 10)
array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [124]:
# Creating 10x10 matrix between values 0 and 5
matrix10_10 = np.linspace(0, 5, 100).reshape(10, 10)
matrix10_10

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

In [125]:
# Creating a 10x10 matrix with values between 0 and 5, without using NumPy

#N = Size of the matrix (10x10)
n =  10  
# I need 100 unique values between 0 and 5 
# I multiply n*n which gives 100 values. Since I want a matrix to go  from 0 to 5, I divide 5 by 99 to get step
step = 5 / 99
# Step is something like 0.050505050505050504

matrix0_5 = [[(i*n + j) * step for j in range(n)] for i in range(n)]
matrix0_5

# For doing this task, I got the basic idea from here: https://www.geeksforgeeks.org/python-produce-k-evenly-spaced-float-values/
# For this task, I spent more time to understand "How to create a list of evenly spaced numbers in Python without NumPy?"

[[0.0,
  0.050505050505050504,
  0.10101010101010101,
  0.15151515151515152,
  0.20202020202020202,
  0.25252525252525254,
  0.30303030303030304,
  0.35353535353535354,
  0.40404040404040403,
  0.45454545454545453],
 [0.5050505050505051,
  0.5555555555555556,
  0.6060606060606061,
  0.6565656565656566,
  0.7070707070707071,
  0.7575757575757576,
  0.8080808080808081,
  0.8585858585858586,
  0.9090909090909091,
  0.9595959595959596],
 [1.0101010101010102,
  1.0606060606060606,
  1.1111111111111112,
  1.1616161616161615,
  1.2121212121212122,
  1.2626262626262625,
  1.3131313131313131,
  1.3636363636363635,
  1.4141414141414141,
  1.4646464646464645],
 [1.5151515151515151,
  1.5656565656565655,
  1.6161616161616161,
  1.6666666666666667,
  1.7171717171717171,
  1.7676767676767677,
  1.8181818181818181,
  1.8686868686868687,
  1.9191919191919191,
  1.9696969696969697],
 [2.0202020202020203,
  2.0707070707070705,
  2.121212121212121,
  2.1717171717171717,
  2.2222222222222223,
  2.27272727

<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [126]:
numbers = [23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51]
matrix3_5 = np.array(numbers).reshape(3, 5)
matrix3_5


array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [127]:
matrix8_16 = np.arange(128, 256).reshape(8, 16)
matrix8_16

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [128]:
matrix = np.linspace(0.05, 5, 100).reshape(10, 10)
matrix

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [129]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [130]:
matrix_1 = dataset[3:, 2:]
matrix_1


array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [131]:
# exercise 1.6c, matrix slicing
matrix_2 = dataset[:4, 3]
matrix_2

array([ 4, 10, 16, 22])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [132]:
matrix_3 =  dataset[2, :]
matrix_3

array([13, 14, 15, 16, 17, 18])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [133]:
matrix_4 = dataset[3:, :]
matrix_4

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises <u><b>without</b></u> NumPy in Python!

<br>
<b>Note:</b> Don't create a new dataset when adding 50 to all values in the array, use the existing one.
<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [134]:
# exercise 1.7, NumPy -operations on a matrix
# use different variable names for each subtask
# you can also make new code cells if you need


In [135]:
dataset_2 = np.arange(1, 50).reshape(7, 7)
dataset_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [136]:
# 1- Adding 50 to all values in the array
matrix_1 = dataset_2 + 50
matrix_1

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [137]:
# 2-Getting the sum of all values in the array
sum = np.sum(dataset_2)
sum

np.int64(1225)

In [138]:
# 3 Getting sum of only odd numbers in the matrix
odd_sum = dataset_2[dataset_2 % 2 != 0].sum()
odd_sum


np.int64(625)

In [139]:
# 4- Getting the standard deviation of the values in the matrix
std = dataset_2.std()   
std

np.float64(14.142135623730951)

In [140]:
# 5- Getting the sum of all values by ROW in the matrix
sum_row = dataset_2.sum(axis=1)
sum_row

array([ 28,  77, 126, 175, 224, 273, 322])

In [141]:
# 6- Getting the sum of all values by COLUMN in the matrix
sum_column = dataset_2.sum(axis=0)
sum_column

array([154, 161, 168, 175, 182, 189, 196])

In [142]:
# 7- Extra task: 
# Doing the total sum, row sum and column sum exercises without NumPy
# I have not found any way to do this without using NumPy yet, I will try to do it again later.

<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


<b> I created a 15x15 matrix randomly in save_matrix.py and saved it as matrix.txt file and then I read it in read_matrix.py.<br>
Both python files and matrix in First assignment folder<b>

<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [143]:
# Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots (for example: -100)
matrix0_50 = np.random.randint(0, 51, size=(15, 15))
matrix0_50


array([[26, 32, 28, 10, 34, 18, 40, 24, 19, 37, 10, 27, 16, 32, 21],
       [ 2, 17, 30, 12,  7, 36, 41, 12, 22, 32,  5, 50, 21, 46,  4],
       [47,  4, 43, 16, 25, 46, 30, 42, 11, 24, 11, 46,  1,  0, 15],
       [20, 15,  7,  5, 27, 35, 26, 13, 20, 36, 42, 43, 46,  3, 36],
       [46, 48, 13, 45, 11, 36, 30, 49, 18,  1, 17, 13,  4, 37, 28],
       [11, 33, 24,  6, 50, 37, 45, 47, 20, 43,  2, 24, 25, 24, 37],
       [44, 29, 14, 43, 26, 44,  1, 21, 10, 18,  7, 18,  4, 32, 12],
       [14,  7, 22, 20, 21, 13,  4, 27, 16,  1, 33, 13, 32, 26, 48],
       [19, 22, 14, 28, 34, 48, 40,  2, 36, 45, 50, 47, 49, 17,  7],
       [15, 12, 49, 11, 42, 28, 19, 15, 14, 50, 20, 24, 40,  1, 14],
       [ 2, 40, 24, 44, 13, 12, 32, 42, 14, 28,  8,  9, 46, 26,  5],
       [26, 21, 17, 13, 27,  5, 41, 31, 44, 17, 29,  1, 27,  4,  8],
       [39,  7, 20,  2, 25, 15,  1,  6, 39, 32, 13, 49,  5, 31, 17],
       [44, 39,  8, 29, 28, 50, 27, 30,  4,  9, 31, 22, 30, 38,  1],
       [ 3,  3, 30, 30, 28, 21, 20, 31, 33,  9, 44, 27, 33, 21, 24]],
      dtype=int32)

In [169]:
# I used np.random.choice to randomly picks up  10 different indexes in the matrix and replaced the values at those indexes with -100.

faulty = 10
index_b = np.random.choice(matrix0_50.size, faulty, replace=False)
np.put(matrix0_50, index_b, -100) 

# I got this function from there: https://www.geeksforgeeks.org/how-to-randomly-insert-nan-in-a-matrix-with-numpy-in-python/

matrix0_50

array([[  26,   32, -100,   10,   34,   18,   40,   24,   19,   37,   10,
          27,   16,   32,   21],
       [   2,   17,   30,   12,    7,   36,   41,   12,   22,   32,    5,
          50, -100,   46,    4],
       [  47, -100,   43,   16,   25,   46,   30, -100,   11,   24,   11,
          46,    1, -100,   15],
       [  20,   15,    7, -100,   27,   35,   26,   13,   20,   36,   42,
          43,   46,    3, -100],
       [  46,   48, -100,   45,   11,   36,   30,   49,   18, -100,   17,
          13,    4,   37, -100],
       [  11,   33,   24,    6,   50,   37,   45,   47,   20,   43,    2,
          24, -100,   24,   37],
       [  44,   29,   14,   43,   26,   44,    1, -100,   10,   18,    7,
          18,    4,   32,   12],
       [  14,    7,   22,   20, -100,   13,    4, -100,   16, -100,   33,
          13,   32,   26,   48],
       [  19, -100,   14,   28,   34,   48,   40,    2,   36,   45,   50,
          47,   49,   17,    7],
       [  15,   12,   49,   11,   42,   28,   19,   15,   14,   50,   20,
          24,   40,    1,   14],
       [   2,   40,   24,   44,   13,   12,   32,   42,   14,   28, -100,
           9,   46,   26,    5],
       [-100,   21,   17,   13, -100,    5,   41, -100,   44, -100,   29,
           1,   27,    4,    8],
       [  39,    7,   20,    2,   25,   15,    1,    6,   39, -100,   13,
        -100,    5,   31, -100],
       [  44,   39,    8,   29,   28,   50,   27,   30,    4,    9,   31,
          22,   30,   38, -100],
       [   3,    3,   30,   30, -100,   21,   20, -100,   33,    9,   44,
        -100,   33, -100,   24]], dtype=int32)

In [171]:
# Replacing the -100 with zero in the matrix
matrix0_50[matrix0_50 == -100] = 0
matrix0_50

array([[26, 32,  0, 10, 34, 18, 40, 24, 19, 37, 10, 27, 16, 32, 21],
       [ 2, 17, 30, 12,  7, 36, 41, 12, 22, 32,  5, 50,  0, 46,  4],
       [47,  0, 43, 16, 25, 46, 30,  0, 11, 24, 11, 46,  1,  0, 15],
       [20, 15,  7,  0, 27, 35, 26, 13, 20, 36, 42, 43, 46,  3,  0],
       [46, 48,  0, 45, 11, 36, 30, 49, 18,  0, 17, 13,  4, 37,  0],
       [11, 33, 24,  6, 50, 37, 45, 47, 20, 43,  2, 24,  0, 24, 37],
       [44, 29, 14, 43, 26, 44,  1,  0, 10, 18,  7, 18,  4, 32, 12],
       [14,  7, 22, 20,  0, 13,  4,  0, 16,  0, 33, 13, 32, 26, 48],
       [19,  0, 14, 28, 34, 48, 40,  2, 36, 45, 50, 47, 49, 17,  7],
       [15, 12, 49, 11, 42, 28, 19, 15, 14, 50, 20, 24, 40,  1, 14],
       [ 2, 40, 24, 44, 13, 12, 32, 42, 14, 28,  0,  9, 46, 26,  5],
       [ 0, 21, 17, 13,  0,  5, 41,  0, 44,  0, 29,  1, 27,  4,  8],
       [39,  7, 20,  2, 25, 15,  1,  6, 39,  0, 13,  0,  5, 31,  0],
       [44, 39,  8, 29, 28, 50, 27, 30,  4,  9, 31, 22, 30, 38,  0],
       [ 3,  3, 30, 30,  0, 21, 20,  0, 33,  9, 44,  0, 33,  0, 24]],
      dtype=int32)

<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [146]:
# Manufacturing years of 10 cars, values between 2010 and 2020
years = np.random.randint(2010, 2021, 10)
years




array([2018, 2020, 2011, 2017, 2012, 2015, 2011, 2010, 2012, 2012],
      dtype=int32)

In [147]:
# Selling price of 10 cars, prices between 2000€ and 60000€
prices = np.random.randint(2000, 60001, 10)
prices

array([51180, 49293, 19688,  2709, 46130, 12499, 29245,  7322, 34775,
        7081], dtype=int32)

In [148]:
# Sorting the years and prices
sort = np.argsort(years)
sorted_years = years[sort]
sorted_prices = prices[sort]

# Creating a DataFrame
df = pd.DataFrame({'Year': sorted_years, 'Price': sorted_prices})
df

Year  Price
0  2010   7322
1  2011  19688
2  2011  29245
3  2012  46130
4  2012   7081
5  2012  34775
6  2015  12499
7  2017   2709
8  2018  51180
9  2020  49293

<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




### 1. np.repeat()

In [149]:
# Repeats each element in an array a specified number of times.
# when you need to duplicate data for creating patterns or expanding datasets
# Example:
# Create an array of 5 elements
array = np.array([1, 2, 3, 4, 5])
array



array([1, 2, 3, 4, 5])

In [150]:
repeat = np.repeat(array, 3)
repeat

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

### 2. np.ravel()

In [151]:
# it converts a multi-dimensional array into a flat (1D) array. 
# It is useful when you need to process data as a single dimension, like for machine learning models.
ravel_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ravel_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
flatten = np.ravel(ravel_array)
flatten

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. np.hsplit(), np.vsplit(), np.hstack, np.vstack()

In [153]:
# hsplit(): Splits an array into equal parts along columns.
# vsplit(): Splits an array into equal parts along rows.
# hstack(): Stacks arrays side by side (columns).
# vstack(): Stacks arrays on top of each other (rows).

In [154]:
# Creating  a 4x4 matrix
matrix = np.arange(1, 17).reshape(4, 4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [155]:
# Split the matrix into two equal parts along columns
hsplit = np.hsplit(matrix, 2)
hsplit


[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [156]:
# Example 2:
# Creating a 6x6 matrix
matrix6_6 = np.arange(1, 37).reshape(6, 6)
matrix6_6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [157]:
# Split the matrix into two equal parts along rows
vsplit = np.vsplit(matrix6_6, 2)
vsplit


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [158]:
# Example 3: 

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stacking the arrays side by side
hstack = np.hstack((array1, array2))
hstack


array([1, 2, 3, 4, 5, 6])

In [159]:
# Stacking the arrays on top of each other
vstack = np.vstack((array1, array2))
vstack

array([[1, 2, 3],
       [4, 5, 6]])

### 4. np.transpose()

In [160]:
# np.transpose()
# Swaps rows and columns in a matrix.  
arr = np.array([[1, 2], [3, 4]])
np.transpose(arr)  


array([[1, 3],
       [2, 4]])

### 5. np.round()

In [161]:
# It is used when formatting results, like rounding predictions to two decimals.

# Example:
arr = np.array([1.123, 2.456])
np.round(arr, 1) 

array([1.1, 2.5])

### 6. np.expand_dims(), np.squeeze()

In [162]:
# expand_dims(): Adds a new dimension to an array.
# squeeze():  Adds a new dimension to an array.

# Example:
arr = np.array([1, 2, 3])
print(arr.shape)

(3,)


In [163]:
# Expanding the dimensions of the array
new_arr = np.expand_dims(arr, axis=1)

new_arr.shape


(3, 1)

In [164]:
# Example 2:

arr = np.array([[[1, 2], [3, 4]]])
print(arr.shape)

# Removing the extra dimension
new_arr = np.squeeze(arr)

print(new_arr.shape)


(1, 2, 2)
(2, 2)


### 7. np.digitiz

In [165]:
# It simplifies complex data, reduces noise, and prepares data for specific algorithms.

a = np.array([1.2, 2.4, 3.6, 4.8])
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0])

# using np.digitize() method
gfg = np.digitize(a, bins)

gfg

array([1, 2, 3, 4])