In [25]:
import numpy  as np

## Create Lists Without NumPy 
1. Create a list of 15 ones.
2. Create a list of 15 number 7's.
3. Create a list of numbers from 100 to 150.
4. Create a list of even numbers between 0 and 100.
5. Create a list of years that are divisible by 4 between 1950 and 2020.


In [131]:
# 1- Create a list of 15 ones without using " Numpy"
one = [1]*15
print(one)


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [132]:
one  = [1 for _ in range(15)]
one

one 

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [133]:
# Create a list of  15 numbers of 7s without using " Numpy"
seven = [7]*15
print(seven)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [134]:
seven = [7 for _ in range(15)]
seven 

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [135]:
# 3- Create a list numbers from 100 to 150 without using " Numpy"

number = [i for i in range(100, 151)]
print(number)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [136]:
# 4- Create a list of even number between 0 to 100 numbers without using " Numpy"
even  = [i for i in range(0, 101) if i % 2 == 0]
even


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [137]:
#-5  Create list of years that are dividable by 4 between 1950 and 2020
years = [i for i in range(1950, 2021) if i % 4 == 0]
years

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016,
 2020]

## Create these arrays with NumPy!
1. Array of 15 zeroes.
2. Array of 15 ones.
3. Array of 15 number 7's.
4. Array of numbers from 100 to 150.
5. Array of numbers from 1900 to 2021.
6. Array of even numbers between 0 and 100.
7. Array of years that are divisible by 4 between 1950 and 2020.


In [139]:
# 1- Create a list of 15 ones using " Numpy"
zero = np.zeros(15)
zero


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [140]:
# 2- Create a list of  15 numbers of 1s using " Numpy"
one = np.ones(15)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [141]:
# 3- Create a array of 15 numbers 7 using " Numpy"
seven = np.full(15, 7)
seven

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [142]:
# 4- Create a list numbers from 100 to 150 using " Numpy"
number = np.arange(100, 151)
number

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [144]:
# 5- Create a list of even number between 0 to 100 numbers using " Numpy"
even = np.arange(0, 101, 2)
even

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [153]:
# 6- Create list of years that are dividable by 4 between 1950 and 2020 using " Numpy"
numbers = np.arange(1950, 2021)
years = numbers[numbers % 4 == 0]
years


array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

## NumPy vectors and matrices:

In [157]:
# Creating  a NumPy vector (list) containing these values: 5, 16, 9, 2, 19, 18, 11, 7
# Use argmax() to find the position index of the largest value in the vector, and print it

vect = np.array([5, 16, 9, 2, 19, 18, 11, 7])

position = np.argmax(vect)
print(position)

# The position index of the 19 in the vector is 4. 


4


In [ ]:
# Creating  a 7x7 matrix, with values from 1 to 49
matrix = np.arange(1, 50).reshape(7, 7)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [167]:
# Extra tasks:
# Creating 7x7 matrix, with values from 1 to 49 without using "Numpy"

matrix = [[i + j for i in range(7)] for j in range(1, 49, 7)]
matrix

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [169]:
# Generating 8x8 random number matrix, values between 0 and 5
matrix = np.random.randint(0, 6, (8, 8))    
matrix

array([[0, 3, 1, 3, 1, 5, 4, 4],
       [5, 0, 5, 4, 3, 0, 2, 5],
       [2, 4, 0, 1, 3, 5, 1, 5],
       [0, 0, 1, 5, 1, 4, 3, 5],
       [3, 0, 4, 5, 5, 1, 5, 0],
       [3, 1, 1, 4, 2, 4, 1, 3],
       [2, 1, 0, 1, 4, 3, 0, 5],
       [5, 3, 2, 0, 0, 5, 0, 5]], dtype=int32)

In [174]:
# Creating  8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)
matrix = np.random.randint(-3, 4, (8, 8))   
matrix

array([[ 2, -1,  3,  3, -3, -3,  3, -1],
       [-3, -3, -2,  3, -2, -1, -3,  3],
       [-2,  1, -3, -1,  1,  3,  1,  2],
       [ 0, -1,  0,  1,  1,  2,  2, -3],
       [ 0, -2,  3,  0, -1,  3, -2, -2],
       [ 1, -3,  1, -1,  3,  2,  3,  1],
       [-1,  1,  1,  2, -2, -1,  0,  1],
       [ 0, -2, -1,  2, -2, -3, -1,  2]], dtype=int32)

In [175]:
#  array (list/vector) of 10 values between value 0 and 1 
array = np.linspace(0, 1, 10)
array

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [177]:
# Creating 10x10 matrix between values 0 and 5
matrix = np.linspace(0, 5, 100).reshape(10, 10)
matrix

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.6363636

In [ ]:
#  Extra task: create this matrix without NumPy as well!# 